### PR TITLE
Only do the mounting and let `runusb` do the running

### PR DESCRIPTION
**Pull request by prophile**

### CODE REVIEW

**Comment by SThomasP** [comment]
Can I just check that runusb unmounts the drive once done?

**Comment by prophile** [comment]
At the moment, it does not—you're wanting it unmounted to avoid corruption?

**Comment by prophile** [comment]
Self-code-review here: needs a `README.md` update

**Comment by prophile** [comment]
@SThomasP thanks, could you nab d28e62f onto `master` while you're in a merging mood? :shipit:

**Pull request merged**
